# Uncomment the next line to define a global platform for your project
 platform :ios, '14.4'

target 'API' do
  # Comment the next line if you don't want to use dynamic frameworks
  #  use_frameworks!
  use_modular_headers!

  # Pods for API
  pod 'Alamofire', '~> 5.4'
end

target 'BookRecommendData' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!

  # Pods for BookRecommendData
  pod 'Alamofire', '~> 5.4'
end

target 'IamSchoolBookRecommend' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!

  # Pods for IamSchoolBookRecommend
  pod 'Kingfisher', '~> 6.3'
end
